#!/usr/bin/env bash
set -euo pipefail

# ── Helpers ───────────────────────────────────────────────────────────
info()  { printf '\033[1;34m▸ %s\033[0m\n' "$*"; }
ok()    { printf '\033[1;32m✓ %s\033[0m\n' "$*"; }
warn()  { printf '\033[1;33m⚠ %s\033[0m\n' "$*"; }
fail()  { printf '\033[1;31m✗ %s\033[0m\n' "$*" >&2; exit 1; }

prompt() {
  local var="$1" label="$2" default="$3"
  local value
  if [ -n "$default" ]; then
    printf '\033[1m%s\033[0m [%s]: ' "$label" "$default"
  else
    printf '\033[1m%s\033[0m: ' "$label"
  fi
  read -r value
  value="${value:-$default}"
  eval "$var=\"\$value\""
}

# ── Pre-checks ────────────────────────────────────────────────────────
command -v docker >/dev/null 2>&1 || fail "Docker is required. Install it first."
command -v openssl >/dev/null 2>&1 || fail "openssl is required for secret generation."

if [ -f .env ]; then
  warn ".env already exists. Running setup will overwrite it."
  printf 'Continue? [y/N]: '
  read -r confirm
  case "$confirm" in
    y|Y|yes|YES) ;;
    *) echo "Aborted."; exit 0 ;;
  esac
fi

echo ""
info "shadownet-local setup"
echo ""

# ── Collect configuration ─────────────────────────────────────────────
prompt EXTERNAL_URL    "Public URL for this instance (https://)" "https://localhost:8340"
prompt ADDRESSING_MODE "Addressing mode (direct|shadowname)" "direct"
SHADOWNAME=""
if [ "$ADDRESSING_MODE" = "shadowname" ]; then
  prompt SHADOWNAME    "Shadowname (local@provider format)" ""
  prompt PROVIDER_DOMAIN "Provider domain you operate (DNS _shadownet.<domain>)" ""
fi
prompt AGENT_NAME    "Agent display name" "shadownet"
prompt OWNER_NAME    "Owner name" "$(whoami)"

# ── Generate secrets ──────────────────────────────────────────────────
JWT_SECRET=$(openssl rand -hex 32)
ok "Generated JWT secret"

# ── Detect agent Docker network ──────────────────────────────────────
info "Looking for agent Docker networks..."
AGENT_NETWORK=""
DETECTED_NETWORKS=$(docker network ls --format '{{.Name}}' 2>/dev/null || true)

if [ -n "$DETECTED_NETWORKS" ]; then
  echo "  Available networks:"
  echo "$DETECTED_NETWORKS" | while read -r net; do echo "    - $net"; done
  echo ""
  prompt AGENT_NETWORK "Docker network to join (for agent access)" "agent-network"
else
  warn "No Docker networks found."
  prompt AGENT_NETWORK "Docker network name (leave empty to create a new one)" "agent-network"
fi

# ── Write .env ────────────────────────────────────────────────────────
cat > .env << EOF
# shadownet-local configuration
# Generated by setup.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)

# Public URL (https:// in production; the AgentCard + connection URI derive from it)
SHADOWNET_EXTERNAL_URL=$EXTERNAL_URL

# Addressing (RFC 0001 §3): direct (key-based, no DNS) or shadowname (provider mode)
SHADOWNET_ADDRESSING_MODE=$ADDRESSING_MODE
SHADOWNET_SHADOWNAME=$SHADOWNAME
SHADOWNET_PROVIDER_DOMAIN=${PROVIDER_DOMAIN:-}

# Identity
SHADOWNET_AGENT_NAME=$AGENT_NAME
SHADOWNET_OWNER_NAME=$OWNER_NAME

# Portal / access-token signing — auto-generated, do not share
SHADOWNET_JWT_SECRET=$JWT_SECRET

# Trust (RFC 0001 §7): JSON list of {issuer, accept}; empty = trust nobody yet
SHADOWNET_TRUST_STORE=[]

# Docker networking
AGENT_NETWORK=$AGENT_NETWORK
EOF

ok "Wrote .env"

# ── Build and start ───────────────────────────────────────────────────
echo ""
prompt DO_START "Start shadownet-local now?" "y"

if [ "$DO_START" = "y" ] || [ "$DO_START" = "Y" ]; then
  info "Building and starting..."
  docker compose up -d --build
  echo ""
  ok "shadownet-local is running"
  echo ""
  echo "  UI: $EXTERNAL_URL"
  echo ""
else
  echo ""
  ok "Setup complete. Start with: docker compose up -d --build"
  echo ""
fi

# ── Next steps ────────────────────────────────────────────────────────
echo "Next steps:"
echo "  1. Open $EXTERNAL_URL and create an account"
echo "  2. Go to Connect → generate a shadow://connect link for your host agent"
echo "  3. Install the host plugin and paste the link (or its mcp= URL + token)"
echo "  4. Share your connection URI (Connect page) so peers can reach you"
echo ""
echo "  For Traefik: docker compose -f docker-compose.yml -f docker-compose.traefik.yml up -d"
echo "  For testing: docker compose -f docker-compose.yml -f docker-compose.test.yml up -d"
