#!/usr/bin/env bash
set -euo pipefail

# ── Helpers ───────────────────────────────────────────────────────────
info()  { printf '\033[1;34m▸ %s\033[0m\n' "$*"; }
ok()    { printf '\033[1;32m✓ %s\033[0m\n' "$*"; }
warn()  { printf '\033[1;33m⚠ %s\033[0m\n' "$*"; }
fail()  { printf '\033[1;31m✗ %s\033[0m\n' "$*" >&2; exit 1; }

prompt() {
  local var="$1" label="$2" default="$3"
  local value
  if [ -n "$default" ]; then
    printf '\033[1m%s\033[0m [%s]: ' "$label" "$default"
  else
    printf '\033[1m%s\033[0m: ' "$label"
  fi
  read -r value
  value="${value:-$default}"
  eval "$var=\"\$value\""
}

# ── Pre-checks ────────────────────────────────────────────────────────
command -v docker >/dev/null 2>&1 || fail "Docker is required. Install it first."
command -v openssl >/dev/null 2>&1 || fail "openssl is required for secret generation."

if [ -f .env ]; then
  warn ".env already exists. Running setup will overwrite it."
  printf 'Continue? [y/N]: '
  read -r confirm
  case "$confirm" in
    y|Y|yes|YES) ;;
    *) echo "Aborted."; exit 0 ;;
  esac
fi

echo ""
info "shadownet setup"
echo ""

# ── Collect configuration ─────────────────────────────────────────────
prompt EXTERNAL_URL "Public URL for this instance" "http://localhost:8340"
prompt AGENT_NAME   "Agent display name"           "shadownet"
prompt OWNER_NAME   "Owner name"                   "$(whoami)"

# ── Generate secrets ──────────────────────────────────────────────────
JWT_SECRET=$(openssl rand -hex 32)
WEBHOOK_SECRET=$(openssl rand -hex 32)
ok "Generated JWT and webhook secrets"

# ── Detect agent Docker network ──────────────────────────────────────
info "Looking for agent Docker networks..."
AGENT_NETWORK=""
DETECTED_NETWORKS=$(docker network ls --format '{{.Name}}' 2>/dev/null || true)

if [ -n "$DETECTED_NETWORKS" ]; then
  echo "  Available networks:"
  echo "$DETECTED_NETWORKS" | while read -r net; do echo "    - $net"; done
  echo ""
  prompt AGENT_NETWORK "Docker network to join (for agent MCP access)" "agent-network"
else
  warn "No Docker networks found."
  prompt AGENT_NETWORK "Docker network name (leave empty to create a new one)" "agent-network"
fi

# ── Webhook configuration ─────────────────────────────────────────────
echo ""
info "Webhook configuration (optional)"
echo "  If your agent runs in Docker on the same network,"
echo "  shadownet can notify it when A2A messages arrive."
echo "  Example: http://<agent-container>:8644/webhooks/a2a-inbox"
echo ""
prompt WEBHOOK_URL "Notification webhook URL (leave empty to skip)" ""

# ── Write .env ────────────────────────────────────────────────────────
cat > .env << EOF
# shadownet configuration
# Generated by setup.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)

# Public URL where this instance is reachable
SHADOWNET_EXTERNAL_URL=$EXTERNAL_URL

# Identity
SHADOWNET_AGENT_NAME=$AGENT_NAME
SHADOWNET_OWNER_NAME=$OWNER_NAME

# Auth — auto-generated, do not share
SHADOWNET_JWT_SECRET=$JWT_SECRET

# Docker networking
AGENT_NETWORK=$AGENT_NETWORK

# Webhook notifications to host agent
SHADOWNET_NOTIFICATION_WEBHOOK_URL=$WEBHOOK_URL
SHADOWNET_NOTIFICATION_WEBHOOK_SECRET=$WEBHOOK_SECRET
EOF

ok "Wrote .env"

# ── Build and start ───────────────────────────────────────────────────
echo ""
prompt DO_START "Start shadownet now?" "y"

if [ "$DO_START" = "y" ] || [ "$DO_START" = "Y" ]; then
  info "Building and starting..."
  docker compose up -d --build
  echo ""
  ok "shadownet is running"
  echo ""
  echo "  UI:  $EXTERNAL_URL"
  echo "  MCP: port 8341 (for agent integration)"
  echo ""
else
  echo ""
  ok "Setup complete. Start with: docker compose up -d --build"
  echo ""
fi

# ── Next steps ────────────────────────────────────────────────────────
echo "Next steps:"
echo "  1. Open $EXTERNAL_URL and create an account"
echo "  2. Add contacts (other shadownet instances)"
echo "  3. Install agent skills: cp -r skills/social/ ~/.hermes/skills/social/"
echo "  4. Configure your agent's webhook routes (see agent-config.example.yaml)"
echo ""
if [ -n "$WEBHOOK_URL" ]; then
  echo "  Webhook secret (add to your agent's config.yaml route):"
  echo "    $WEBHOOK_SECRET"
  echo ""
fi
echo "  For Traefik: docker compose -f docker-compose.yml -f docker-compose.traefik.yml up -d"
echo "  For testing: docker compose -f docker-compose.yml -f docker-compose.test.yml up -d"
